// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbjgvcpfgrqhkooxlohn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxiamd2Y3BmZ3JxaGtvb3hsb2huIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NzE5MjAsImV4cCI6MjA3MDE0NzkyMH0.QvQ2jYccuuBD4HVgyDXNMgIZ29PzPoF5OztSgwFzerw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});